### ISSUE TITLE
getSkylinkUrl with subdomain setting returns url with trailing slash

### ISSUE THREAD

**Issue by kwypchlo** [SkynetLabs/skynet-js#34] opened 2021-04-08 15:07 UTC
```javascript
client.getSkylinkUrl("sia:_AiuN_5DuPir4GWPxXPFxlnM8MrbHR1ZDksN4IhfphiJzw", { subdomain: true });

// returned: https://vg4asdvu8esfhav0cm7sasu5opcsps6arcehqm8e9c6u122vkoc8jjo.siasky.net/
```

I was expecting url without trailing slash.

```javascript
// expected: https://vg4asdvu8esfhav0cm7sasu5opcsps6arcehqm8e9c6u122vkoc8jjo.siasky.net
```

**Comment by m-cat** [comment] 2021-04-30 14:53
Can't reproduce, closing

**Closed by m-cat** 2021-04-30 14:53 UTC
